#!/usr/bin/env python

"""
.. module:: compareResults
   :synopsis: Compare sms files generated by Fastlim and SmodelS

.. moduleauthor:: Andre Lessa <lessa.a.p@gmail.com>

"""
import sys,os,glob
import logging
sys.path.append('../runTools')
home = os.path.expanduser("~")
sys.path.append(os.path.join(home,'smodels'))
from fastlimOutput import compareFiles
from collections import OrderedDict
from smodels.tools.physicsUnits import GeV, fb, TeV

FORMAT = '%(levelname)s in %(module)s.%(funcName)s() in %(lineno)s: %(message)s'
logging.basicConfig(format=FORMAT)
logger = logging.getLogger(__name__)


fastlimDir = './SLHA/test_fastlim'
smodelsDir = './SLHA/test_smodels'

fastFiles = glob.glob(os.path.join(fastlimDir,'*.sms'))
smodelsFiles = glob.glob(os.path.join(smodelsDir,'*.sms'))


for f in fastFiles:
    fname = f[f.rfind('/')+1:]
    if not os.path.join(smodelsDir,fname) in smodelsFiles: continue
    #First check additional data (consistency check)
    if not compareFiles(f,os.path.join(smodelsDir,fname),allowedDiff=0.01,
                        ignore=['ExptRes','extra']):
        logger.error("Data in %s have differ" %fname)
        sys.exit()

    #Check experimental results:
    allRes = []
    sigcut = 0.
    for ff in [os.path.join(smodelsDir,fname),f]:
        fin = open(ff,'r')
        dic = eval(fin.read().replace(' [fb]','*fb').replace('[GeV]','*GeV'))
        sigcut = max(sigcut,dic['extra']['sigmacut'])
        exptRes = dic['ExptRes']
        if ff == f:
            for iexp,exp in enumerate(exptRes[:]):
                if exp['tval'] < 10.*sigcut: exptRes[iexp] = None 
            while None in exptRes: exptRes.remove(None)
        allRes.append(sorted(exptRes,  key=lambda k: k['AnalysisName']))
        
    sres,fres = allRes
    print fres,'\n\n'
    print sres
    sys.exit()