all: feynmangraphs

feynmangraphs: .PHONY
	./feynmanGraph.py -s -i -c "[[*],[]]" -f '["MET","HSCP"]' -o THSCPM2b.png 
#	./feynmanGraph.py -s -i -c "[[[*]],[[*]]]" -f '["HSCP","HSCP"]' -o THSCPM3.png
#	./feynmanGraph.py -s -i -c "[[[q,q]],[[q,q]]]" -o T1.png
#	./feynmanGraph.py -s -i -c "[[],[]]" -o TRHadGM1.png  -f '["RHadronG","RHadronG"]'

.PHONY:
